### ISSUE TITLE
Commands binaryes

### ISSUE THREAD

**Issue by Mugaduka** [N-HANS/N-HANS#1]
Hi. In Readme you wrote about commands: nhans_denoiser, nhans_separator, model loaders. How can I get it?
Thanks

**Comment by N-HANS** [comment]
Hi,

If you use pip install N-HANS in terminal, all commands like 
nhans_denosier , nhans_separator, and load_denoiser, load_separator will 
be automatically installed. load_denoiser and load_separator will help 
you to set up N-HANS. And nhans_denoiser and nhans_separator are used to 
apply N-HANS.

Thanks and viel Spass


Am 2019-11-19 11:01, schrieb Mugaduka:
> Hi. In Readme you wrote about commands: nhans_denoiser,
> nhans_separator, model loaders. How can I get it?
> Thanks

**Comment by Mugaduka** [comment]
Thanks a lot!
I found it in ~/.local/bin
